# Generated by Django 4.2 on 2023-06-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_header', models.CharField(blank=True, max_length=100, null=True)),
                ('second_header', models.CharField(blank=True, max_length=200, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('header_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('header_image2', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, help_text='add the header', max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetailPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of your book', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Re-type the name of your book', max_length=200, null=True, unique=True)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(help_text='A short description of your book')),
                ('quote', models.CharField(blank=True, max_length=300, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Choose keywords to locate your book easier', max_length=250, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('book', models.FileField(help_text='Upload your book here', null=True, upload_to='books/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Published', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comment_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('messagename', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EditorialMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('consulting_editor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_author', models.CharField(blank=True, help_text='Seo author name', max_length=200, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Seo description', max_length=200, null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='Seo keywords', null=True)),
                ('title', models.CharField(blank=True, default='My site', help_text='Name of your site', max_length=200, null=True)),
                ('favicon', models.ImageField(blank=True, help_text='image that appears on your url', null=True, upload_to='')),
                ('logo', models.ImageField(blank=True, help_text='Logo that appears on your site', null=True, upload_to='')),
                ('site_description', models.CharField(blank=True, help_text='A logo alternative in written form', max_length=300, null=True)),
                ('footer_title', models.CharField(blank=True, help_text='Your footer title', max_length=300, null=True)),
                ('footer_description', models.CharField(blank=True, help_text='Your footer description', max_length=300, null=True)),
                ('facebook', models.URLField(blank=True, help_text='Facebook url', null=True)),
                ('Twitter', models.URLField(blank=True, help_text='Twitter url', null=True)),
                ('Instagram', models.URLField(blank=True, help_text='Instagram url', null=True)),
                ('linkedIn', models.URLField(blank=True, help_text='Linkedin url', null=True)),
                ('Address', models.CharField(blank=True, help_text='Your Address', max_length=1000, null=True)),
                ('Tel', models.IntegerField(blank=True, help_text='Your phone number', null=True)),
                ('Email', models.EmailField(blank=True, help_text='Your Email Address', max_length=254, null=True)),
                ('Working_hours', models.CharField(blank=True, help_text='Your specific working hours', max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Owner_Detail',
                'verbose_name_plural': 'Owner_Details',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the person making a comment', max_length=200, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email of the person making a comment', max_length=254, null=True)),
                ('description', models.TextField(blank=True, help_text='The comment made', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date created', null=True)),
                ('comment', models.ForeignKey(blank=True, help_text='Numberof comments in a post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='academic_journals_app.bookdetailpost')),
            ],
        ),
        migrations.AddField(
            model_name='bookdetailpost',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose the ctegory your book fall in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='academic_journals_app.category'),
        ),
    ]
